### ISSUE TITLE
add base admin panel - delete article

### ISSUE THREAD

**Issue by 8area8** [8area8/plenkton-api#44]
## Context

We need to manage the articles easily

## Todo

- [ ] When connected as admin, we should see a delete icon on articles
- [ ] Click on delete icon display a dialog box
- [ ] click on confirm button delete the article
- [ ] article deleted emit reupload of all articles
