### ISSUE TITLE
Use of doit

### ISSUE THREAD

**Issue by 8area8** [8area8/plenkton-api#46]
## Context

We need doit to create admin user, for example

## Todo

- [x] install python doit
- [x] create add_admin command
- [x] create reset_db command
- [x] install fixtures command
- [x] migrate command
